language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

install:
  - apt update
  - apt install -y axel
  - ./rebuild.sh
  - docker-compose up -d

script:
  - pip install -r requirements.txt
  - python3 testsendreq.py
